---
- name: Upgrade existing packages
  gather_facts: no
  become: yes
  hosts: all
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400

- name: Install development packages
  gather_facts: no
  become: yes
  hosts: all
  tasks:
    - name: Install editors
      ansible.builtin.apt:
        pkg:
          - nano
          - vim
          - neovim
    - name: Install git
      ansible.builtin.apt:
        name: git
    - name: Install base development packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - gcc
          - make
          - cmake
          - ninja-build
          - meson
          - gdb

- name: Install SNAP
  gather_facts: no
  become: yes
  hosts: all
  tasks:
    - name: Install SNAP
      ansible.builtin.apt:
        name: snapd

- name: Install Docker
  gather_facts: no
  become: yes
  hosts: all
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Install Docker GPG key and repositories
      ansible.builtin.script: ./scripts/add-docker-repo.sh
      register: dockerscript
      changed_when: "'GPG key and repository lists already exists' not in dockerscript.stdout"
    - name: Install Docker packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Test Docker
      ansible.builtin.shell: "docker run --rm -it hello-world:latest && docker rmi hello-world:latest"
      changed_when: false
